sudo: false
language: php
php:
  - 7.0
  - 5.6
  - nightly

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
    - php artisan migrate
    - php artisan db:seed
    - php artisan clear-compiled
    - vendor/bin/phpunit
