sudo: false
language: php
php:
  - 7.0
  - 5.6
  - nightly

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - sudo chown -R apache:apache bootstrap/cache
  - vendor/bin/phpunit
